// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC5RKrIfvCl6gvfnpGkgWSODeLdI_HyYY',
    appId: '1:104899449297:web:c2c7436bfbc357d43810f0',
    messagingSenderId: '104899449297',
    projectId: 'dig-id',
    authDomain: 'dig-id.firebaseapp.com',
    storageBucket: 'dig-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1VSeVQE001xMF62ppHeboaqm0hKtBAc',
    appId: '1:104899449297:android:e6d2b224eff770b53810f0',
    messagingSenderId: '104899449297',
    projectId: 'dig-id',
    storageBucket: 'dig-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0JvUhAEeAlYxn4bPDMX5e9EnH7iIMC4Y',
    appId: '1:104899449297:ios:d54bd6ef1d30be993810f0',
    messagingSenderId: '104899449297',
    projectId: 'dig-id',
    storageBucket: 'dig-id.appspot.com',
    iosBundleId: 'com.example.erhsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0JvUhAEeAlYxn4bPDMX5e9EnH7iIMC4Y',
    appId: '1:104899449297:ios:473d7453ddc289653810f0',
    messagingSenderId: '104899449297',
    projectId: 'dig-id',
    storageBucket: 'dig-id.appspot.com',
    iosBundleId: 'com.example.erhsApp.RunnerTests',
  );
}
